name: Process Reels

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

jobs:
  edit_reels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install moviepy==1.0.3 Pillow imageio[ffmpeg] requests numpy
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          echo "âœ… Dependencies installed"

      - name: Run video editor script
        run: python auto_edit_my_reels.py

      - name: Commit and push processed files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add output_reels
          git commit -m "Processed reels automatically"
          git push
